language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "4"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script: npm run test-ci
after_success: npm run coveralls