language: node_js
node_js:
  - "6.9.1"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script: ./node_modules/.bin/tape test/api.js